APP_NAME: "server"
APP_PORT: "8000"

DB_DRIVER: "mysql"
DB_HOST: "localhost"
DB_PORT: 3306
DB_NAME: "library_db"
DB_USER: "root"
DB_PASSWORD: "msc1234567"
DB_MAX_POOL_SIZE: 5
DB_MAX_OPEN_CONS: 5
DB_MAX_LIFE_TIME_MINS: 30
MIGRATION_PATH: "./migrations"
